import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import '@mantine/core/styles.css'
import 'react-toastify/dist/ReactToastify.css'
import './global.css'

import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import type { Metadata } from 'next'
import { ToastContainer } from 'react-toastify'
import { Providers } from '@/store/provider'
import { Header } from '@/widgets'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className="main">
				<Providers>
					<MantineProvider>
						<Header />
						{children}
					</MantineProvider>
					<ToastContainer />
				</Providers>
			</body>
		</html>
	)
}
